sudo: required
services:
    - docker

before_install:
    - docker build -t zuhairahamed/docker-react -f Dockerfile.dev .

script:
    - docker run zuhairahamed/docker-react npm run test -- --coverage